package calculadora;

public class ClsDatos extends javax.swing.JFrame {

    String operador = "";
    String contenido;
    boolean CambioEstado;
    float valor1 = 0, valor2 = 0;
    float total = 0;
    private boolean punto = true;

    public ClsDatos() {
        initComponents();
        this.setTitle("Calculadora");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Presultados = new javax.swing.JPanel();
        Lresultado = new javax.swing.JLabel();
        Ltotales = new javax.swing.JLabel();
        Pnumeros = new javax.swing.JPanel();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        Bpunto = new javax.swing.JButton();
        B0 = new javax.swing.JButton();
        Bigual = new javax.swing.JButton();
        Poperaciones = new javax.swing.JPanel();
        Bborrar = new javax.swing.JButton();
        Bdivision = new javax.swing.JButton();
        Bmulti = new javax.swing.JButton();
        Bresta = new javax.swing.JButton();
        Bsuma = new javax.swing.JButton();
        Lfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Presultados.setBackground(new java.awt.Color(255, 255, 255));
        Presultados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Lresultado.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Lresultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        Ltotales.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout PresultadosLayout = new javax.swing.GroupLayout(Presultados);
        Presultados.setLayout(PresultadosLayout);
        PresultadosLayout.setHorizontalGroup(
            PresultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ltotales, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
            .addComponent(Lresultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PresultadosLayout.setVerticalGroup(
            PresultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PresultadosLayout.createSequentialGroup()
                .addComponent(Ltotales, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(Presultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 340, -1));

        Pnumeros.setBackground(new java.awt.Color(255, 255, 255));
        Pnumeros.setLayout(new java.awt.GridLayout(4, 3));

        B7.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        B7.setText("7");
        B7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });
        Pnumeros.add(B7);

        B8.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        B8.setText("8");
        B8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });
        Pnumeros.add(B8);

        B9.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        B9.setText("9");
        B9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });
        Pnumeros.add(B9);

        B4.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        B4.setText("4");
        B4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        Pnumeros.add(B4);

        B5.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        B5.setText("5");
        B5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        Pnumeros.add(B5);

        B6.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        B6.setText("6");
        B6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        Pnumeros.add(B6);

        B1.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        B1.setText("1");
        B1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        Pnumeros.add(B1);

        B2.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        B2.setText("2");
        B2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        Pnumeros.add(B2);

        B3.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        B3.setText("3");
        B3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        Pnumeros.add(B3);

        Bpunto.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Bpunto.setText(".");
        Bpunto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpuntoActionPerformed(evt);
            }
        });
        Pnumeros.add(Bpunto);

        B0.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        B0.setText("0");
        B0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0ActionPerformed(evt);
            }
        });
        Pnumeros.add(B0);

        Bigual.setBackground(new java.awt.Color(51, 102, 255));
        Bigual.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Bigual.setText("=");
        Bigual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BigualActionPerformed(evt);
            }
        });
        Pnumeros.add(Bigual);

        getContentPane().add(Pnumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 320, 250));

        Poperaciones.setBackground(new java.awt.Color(255, 255, 255));
        Poperaciones.setLayout(new java.awt.GridLayout(5, 0));

        Bborrar.setBackground(java.awt.Color.orange);
        Bborrar.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Bborrar.setText("AC");
        Bborrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BborrarActionPerformed(evt);
            }
        });
        Poperaciones.add(Bborrar);

        Bdivision.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Bdivision.setText("÷");
        Bdivision.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bdivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdivisionActionPerformed(evt);
            }
        });
        Poperaciones.add(Bdivision);

        Bmulti.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Bmulti.setText("x");
        Bmulti.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmultiActionPerformed(evt);
            }
        });
        Poperaciones.add(Bmulti);

        Bresta.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Bresta.setText("-");
        Bresta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrestaActionPerformed(evt);
            }
        });
        Poperaciones.add(Bresta);

        Bsuma.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Bsuma.setText("+");
        Bsuma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsumaActionPerformed(evt);
            }
        });
        Poperaciones.add(Bsuma);

        getContentPane().add(Poperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 80, 250));

        Lfondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mario\\OneDrive\\Escritorio\\FondoNumerico.jpg")); // NOI18N
        Lfondo.setText("jLabel1");
        getContentPane().add(Lfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        Lresultado.setText(Lresultado.getText() + "1");
        AlmacenarValores();
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        Lresultado.setText(Lresultado.getText() + "2");
        AlmacenarValores();
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        Lresultado.setText(Lresultado.getText() + "3");
        AlmacenarValores();
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        Lresultado.setText(Lresultado.getText() + "4");
        AlmacenarValores();
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        Lresultado.setText(Lresultado.getText() + "5");
        AlmacenarValores();
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        Lresultado.setText(Lresultado.getText() + "6");
        AlmacenarValores();
    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        Lresultado.setText(Lresultado.getText() + "7");
        AlmacenarValores();
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        Lresultado.setText(Lresultado.getText() + "8");
        AlmacenarValores();
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        Lresultado.setText(Lresultado.getText() + "9");
        AlmacenarValores();
    }//GEN-LAST:event_B9ActionPerformed

    private void B0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0ActionPerformed
        Lresultado.setText(Lresultado.getText() + "0");
        AlmacenarValores();
    }//GEN-LAST:event_B0ActionPerformed

    private void BdivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdivisionActionPerformed
        CambioEstado = true;
        operador = "÷";
        Lresultado.setText("");
        Ltotales.setText(valor1 + " " + operador);
    }//GEN-LAST:event_BdivisionActionPerformed

    private void BmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmultiActionPerformed
        CambioEstado = true;
        operador = "x";
        Lresultado.setText("");
        Ltotales.setText(valor1 + " " + operador);
    }//GEN-LAST:event_BmultiActionPerformed

    private void BrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrestaActionPerformed
        CambioEstado = true;
        operador = "-";
        Lresultado.setText("");
        Ltotales.setText(valor1 + " " + operador);
    }//GEN-LAST:event_BrestaActionPerformed

    private void BsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsumaActionPerformed
        CambioEstado = true;
        operador = "+";
        Lresultado.setText("");
        Ltotales.setText(valor1 + " " + operador);
    }//GEN-LAST:event_BsumaActionPerformed

    private void BigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BigualActionPerformed
        switch (operador) {
            case "+":
                Suma sum = new Suma(valor1, valor2);
                total = sum.Sumar();
                break;
            case "-":
                Resta rest = new Resta(valor1, valor2);
                total = rest.Restar();
                break;
            case "x":
                Multiplicacion mult = new Multiplicacion(valor1, valor2);
                total = mult.Multiplicar();
                break;
            case "÷":
                Division divi = new Division(valor1, valor2);
                total = divi.Dividir();
                break;
        }
        Ltotales.setText(String.valueOf(valor1) + " " + operador + " " + String.valueOf(valor2) + " = ");
        Lresultado.setText(String.valueOf(total));
        valor1 = total;
    }//GEN-LAST:event_BigualActionPerformed

    private void BborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BborrarActionPerformed
        Lresultado.setText("");
        Ltotales.setText("");
        valor1 = 0;
        valor2 = 0;
        total = 0;
        CambioEstado = false;
    }//GEN-LAST:event_BborrarActionPerformed

    private void BpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpuntoActionPerformed
        contenido = Lresultado.getText();
        if (contenido.length() <= 0) {
            Lresultado.setText("0.");
        } else if (Lresultado.getText().contains(".")) {
        } else {
            Lresultado.setText(Lresultado.getText() + ".");
            punto = false;
        }
    }//GEN-LAST:event_BpuntoActionPerformed
    private void AlmacenarValores() {
        if (CambioEstado == false) {
            valor1 = Float.parseFloat(Lresultado.getText());
        } else {
            valor2 = Float.parseFloat(Lresultado.getText());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClsDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClsDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClsDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClsDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClsDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B0;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton Bborrar;
    private javax.swing.JButton Bdivision;
    private javax.swing.JButton Bigual;
    private javax.swing.JButton Bmulti;
    private javax.swing.JButton Bpunto;
    private javax.swing.JButton Bresta;
    private javax.swing.JButton Bsuma;
    private javax.swing.JLabel Lfondo;
    private javax.swing.JLabel Lresultado;
    private javax.swing.JLabel Ltotales;
    private javax.swing.JPanel Pnumeros;
    private javax.swing.JPanel Poperaciones;
    private javax.swing.JPanel Presultados;
    // End of variables declaration//GEN-END:variables
}
